import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import AppLayout from "@/components/layouts/app-layout";
import Script from "next/script";
import "highlight.js/styles/github-dark.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="dark">
        <>
          <AppLayout>{children}</AppLayout>
        </>
      </body>
    </html>
  );
}
